<?php

namespace Tests\Feature\Filament;

use App\Filament\Tenant\Resources\Hotspots\Pages\CreateHotspot;
use App\Filament\Tenant\Resources\Hotspots\Pages\EditHotspot;
use App\Filament\Tenant\Resources\Hotspots\Pages\ListHotspots;
use App\Filament\Tenant\Resources\Hotspots\RelationManagers\PackagesRelationManager;
use App\Models\Hotspot;
use App\Models\Package;
use App\Models\Tenant;
use Filament\Actions\Testing\TestAction;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class HotspotResourceTest extends TestCase
{
    use RefreshDatabase;

    private Tenant $alice;
    private Tenant $bob;

    protected function setUp(): void
    {
        parent::setUp();

        $this->alice = Tenant::factory()->create();
        $this->bob = Tenant::factory()->create();

        $this->actingAs($this->alice, 'tenant');
    }

    public function test_the_list_page_loads(): void
    {
        $this->get('/dashboard/hotspots')->assertOk();
    }

    public function test_only_the_signed_in_tenants_hotspots_are_listed(): void
    {
        $mine = Hotspot::factory()->for($this->alice, 'tenant')->create();
        $theirs = Hotspot::factory()->for($this->bob, 'tenant')->create();

        Livewire::test(ListHotspots::class)
            ->assertCanSeeTableRecords([$mine])
            ->assertCanNotSeeTableRecords([$theirs]);
    }

    public function test_a_hotspot_is_created_against_the_signed_in_tenant(): void
    {
        Livewire::test(CreateHotspot::class)
            ->fillForm([
                'name' => 'Corner Cafe',
                'ssid' => 'corner-cafe',
                'location' => 'Kabalagala',
            ])
            ->call('create')
            ->assertHasNoFormErrors();

        $this->assertDatabaseHas('hotspots', [
            'name' => 'Corner Cafe',
            'tenant_id' => $this->alice->id,
        ]);
    }

    /**
     * url_name drives the public portal URL and is generated by a model event
     * after insert, not supplied by the form.
     */
    public function test_a_created_hotspot_gets_a_portal_url_name(): void
    {
        Livewire::test(CreateHotspot::class)
            ->fillForm(['name' => 'Corner Cafe', 'ssid' => 'corner-cafe'])
            ->call('create');

        $this->assertNotNull(Hotspot::where('name', 'Corner Cafe')->first()->url_name);
    }

    public function test_another_tenants_hotspot_cannot_be_opened_for_editing(): void
    {
        $theirs = Hotspot::factory()->for($this->bob, 'tenant')->create();

        $this->get("/dashboard/hotspots/{$theirs->id}/edit")->assertNotFound();
    }

    public function test_a_package_can_be_added_through_the_relation_manager(): void
    {
        $hotspot = Hotspot::factory()->for($this->alice, 'tenant')->create();

        Livewire::test(PackagesRelationManager::class, [
            'ownerRecord' => $hotspot,
            'pageClass' => EditHotspot::class,
        ])
            ->callAction(TestAction::make('create')->table(), [
                'name' => '2 Hours',
                'price' => 1000,
                'duration_value' => 2,
                'duration_unit' => 'hours',
            ])
            ->assertHasNoActionErrors();

        $this->assertDatabaseHas('packages', [
            'name' => '2 Hours',
            'hotspot_id' => $hotspot->id,
        ]);
    }

    /**
     * sort_order is NOT NULL in the schema. A blank field must land as 0
     * rather than null - the failure this guards against was a 500 on save.
     */
    public function test_a_package_saves_with_a_blank_sort_order(): void
    {
        $hotspot = Hotspot::factory()->for($this->alice, 'tenant')->create();

        Livewire::test(PackagesRelationManager::class, [
            'ownerRecord' => $hotspot,
            'pageClass' => EditHotspot::class,
        ])
            ->callAction(TestAction::make('create')->table(), [
                'name' => 'Daily',
                'price' => 2000,
                'sort_order' => null,
                'data_limit_mb' => null,
                'duration_value' => null,
            ])
            ->assertHasNoActionErrors();

        $package = Package::where('name', 'Daily')->first();

        $this->assertNotNull($package);
        $this->assertSame(0, (int) $package->sort_order);
        $this->assertNull($package->data_limit_mb);
    }

    public function test_two_packages_on_one_hotspot_cannot_share_a_name(): void
    {
        $hotspot = Hotspot::factory()->for($this->alice, 'tenant')->create();
        Package::factory()->for($hotspot)->create(['name' => 'Daily']);

        Livewire::test(PackagesRelationManager::class, [
            'ownerRecord' => $hotspot,
            'pageClass' => EditHotspot::class,
        ])
            ->callAction(TestAction::make('create')->table(), [
                'name' => 'Daily',
                'price' => 2000,
            ])
            ->assertHasActionErrors(['name']);

        $this->assertSame(1, Package::where('hotspot_id', $hotspot->id)->count());
    }

    /**
     * The same package name on a DIFFERENT hotspot is fine - the constraint
     * is per hotspot, not global.
     */
    public function test_the_same_package_name_is_allowed_on_another_hotspot(): void
    {
        $first = Hotspot::factory()->for($this->alice, 'tenant')->create();
        $second = Hotspot::factory()->for($this->alice, 'tenant')->create();
        Package::factory()->for($first)->create(['name' => 'Daily']);

        Livewire::test(PackagesRelationManager::class, [
            'ownerRecord' => $second,
            'pageClass' => EditHotspot::class,
        ])
            ->callAction(TestAction::make('create')->table(), ['name' => 'Daily', 'price' => 2000])
            ->assertHasNoActionErrors();

        $this->assertSame(2, Package::where('name', 'Daily')->count());
    }
}
