<?php

namespace App\Filament\Tenant\Resources\Hotspots\Pages;

use App\Filament\Tenant\Resources\Hotspots\HotspotResource;
use Filament\Resources\Pages\CreateRecord;

class CreateHotspot extends CreateRecord
{
    protected static string $resource = HotspotResource::class;

    /**
     * The owning tenant comes from the guard, never from the form.
     * url_name is generated by a model event after insert.
     */
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['tenant_id'] = \Illuminate\Support\Facades\Auth::guard('tenant')->id();

        return $data;
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
}
